#!/bin/sh
# postinst script for eternallands-data
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
	configure)
	
	TARGETDIR="/usr/share/games/EternalLands"
	CACHEDIR="/var/cache/eternallands"
	DOWNLOADURL="http://twinmoons.org.uk/el/rel/193"
	DOWNLOADMAIN="el_190_linux_data.zip"
	MD5SUMMAIN="28b8563080386a9401848c36d21a839d"
	DOWNLOADMAIN193="el_linux_193.zip"
	MD5SUMMAIN193="df8c47f5f3fe9aaaeec5b1332217b8c0"
	DOWNLOADPATCH190="el_linux_190_update.zip"
	MD5SUMPATCH190="6c88fb3a4e799fbcfa99e7c90215627b"
	DOWNLOADUPDATE191="el_linux_update_191.zip"
	MD5SUMUPDATE191="2f552c2c3f8c9a2541fcb72d4c2be09b"
	DOWNLOADUPDATE192="el_linux_update_192.zip"
	MD5SUMUPDATE192="65c133b6e4ce4d09fbc1976960598087"
	DOWNLOADUPDATE193="el_linux_update_193.zip"
	MD5SUMUPDATE193="455ffe559079b49c752bd51aaaf94f7e"

	[ -f ~paul/el/installpkg/localdownload ] && DOWNLOADURL="http://harry/~paul/el"

	mkdir -p $CACHEDIR
	cd $CACHEDIR
	
	# remove old downloads
	rm -f el_170_linux.zip* el_190_rc2_extra.zip* el_190_rc2.zip* el_update_180.zip* \
		el_update_191_rc*.zip* EternalLands-update_191_2.zip* el_192_rc2.zip

	# if we already have an archive check the md5sum is ok and remove if not
	[ ! -f "$DOWNLOADMAIN" ] || echo "$MD5SUMMAIN  $DOWNLOADMAIN" | md5sum -c - || rm -fv $DOWNLOADMAIN
	[ ! -f "$DOWNLOADMAIN193" ] || echo "$MD5SUMMAIN193  $DOWNLOADMAIN193" | md5sum -c - || rm -fv $DOWNLOADMAIN193
	[ -z "$DOWNLOADPATCH190" ] || [ ! -f $DOWNLOADPATCH190 ] || echo "$MD5SUMPATCH190  $DOWNLOADPATCH190" | md5sum -c - || rm -fv $DOWNLOADPATCH190
	[ -z "$DOWNLOADUPDATE191" ] || [ ! -f $DOWNLOADUPDATE191 ] || echo "$MD5SUMUPDATE191  $DOWNLOADUPDATE191" | md5sum -c - || rm -fv $DOWNLOADUPDATE191
	[ -z "$DOWNLOADUPDATE192" ] || [ ! -f $DOWNLOADUPDATE192 ] || echo "$MD5SUMUPDATE192  $DOWNLOADUPDATE192" | md5sum -c - || rm -fv $DOWNLOADUPDATE192
	[ -z "$DOWNLOADUPDATE193" ] || [ ! -f $DOWNLOADUPDATE193 ] || echo "$MD5SUMUPDATE193  $DOWNLOADUPDATE193" | md5sum -c - || rm -fv $DOWNLOADUPDATE193
	
	UNPACKDIR="`mktemp -d /tmp/eternallands-data.XXXXXXXXXX`"
	
	# if we have all the old files, just download the 193 update
	if [ -f "$DOWNLOADMAIN" -a -f "$DOWNLOADPATCH190" -a -f "$DOWNLOADUPDATE191" -a -f "$DOWNLOADUPDATE192" ]
	then
		if [ -n "$DOWNLOADUPDATE193" -a ! -f "$DOWNLOADUPDATE193" ]
		then
			wget -P "." -v --progress="dot:mega" $DOWNLOADURL/$DOWNLOADUPDATE193
			echo "$MD5SUMUPDATE193  $DOWNLOADUPDATE193" | md5sum -c -
		fi
		# unpack the archives
		cd $UNPACKDIR
		unzip -q $CACHEDIR/$DOWNLOADMAIN
		mv EternalLands-Test4 el_install
		[ -z "$DOWNLOADPATCH190" ] || unzip -o -q $CACHEDIR/$DOWNLOADPATCH190
		mv el_install el_linux_update
		[ -z "$DOWNLOADUPDATE191" ] || unzip -o -q $CACHEDIR/$DOWNLOADUPDATE191
		mv el_linux_update el_update
		[ -z "$DOWNLOADUPDATE192" ] || unzip -o -q $CACHEDIR/$DOWNLOADUPDATE192
		[ -z "$DOWNLOADUPDATE193" ] || unzip -o -q $CACHEDIR/$DOWNLOADUPDATE193
		mv el_update el_install
	# no old stuff so use existing new main or download it
	else
		if [ ! -f "$DOWNLOADMAIN193" ]
		then
			wget -P "." -v --progress="dot:mega" $DOWNLOADURL/$DOWNLOADMAIN193
			echo "$MD5SUMMAIN193  $DOWNLOADMAIN193" | md5sum -c -
		fi
		cd $UNPACKDIR
		unzip -q $CACHEDIR/$DOWNLOADMAIN193
		mv el_linux el_install
	fi

	# fix el.ini and server.lst, remove unneeded files and set the permissions
	cd el_install
	rm -f *.dll *.exe el.*.bin
	sed -i 's/^#data_dir.*$/#data_dir = \/usr\/share\/games\/EternalLands/g' el.ini
	sed -i 's/^#browser.*$/#browser = x-www-browser/g' el.ini
	grep -v ^official servers.lst > sl
	mv sl servers.lst
	chown -R root:root .
	chmod -R a=rX .
	
	# make the file lists
	FILELIST="eternallands-data.filelist"
	DIRLIST="eternallands-data.dirlist"
	find . -type f -exec echo \"{}\" \; > $TARGETDIR/$FILELIST
	find . -type d ! -name "." -exec echo \"{}\" \; | sort -r > $TARGETDIR/$DIRLIST
	
	# remove any existing files in the lists then move the new files into the target directory
	cd $TARGETDIR/
	[ ! -s $FILELIST ] || cat $FILELIST | xargs rm -f || true
	[ ! -s $DIRLIST ] || cat $DIRLIST | xargs rmdir --ignore-fail-on-non-empty > /dev/null 2>&1 || true
	chmod -R +w .
	cp --remove-destination -rpf $UNPACKDIR/el_install/* .
	
	rm -rf $UNPACKDIR
	
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
