/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#define OPEN_3D_OBJ 1
#define OPEN_2D_OBJ 2
#define OPEN_MAP    3
#define SAVE_MAP    4
#define OPEN_PARTICLES_OBJ 5
#define SAVE_PARTICLE_DEF 6

extern char* selected_file;
extern int continue_with;
extern GtkWidget* file_selector;
extern GtkWidget* create_fileselection (void);

