#ifdef GTK2

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
#include "global.h"

char map_file_name[256]={0};
char particle_file_name[256]={0};

char * selected_file=NULL;
GtkWidget * gtk_open_win=NULL;
GtkWidget * gtk_save_win=NULL;

GtkFileFilter * e3d_filter=NULL;
GtkFileFilter * e2d_filter=NULL;
GtkFileFilter * map_filter=NULL;
GtkFileFilter * part_filter=NULL;

void init_filters()
{	
	e3d_filter=gtk_file_filter_new();
	gtk_file_filter_set_name(e3d_filter, "3D object");
	gtk_file_filter_add_pattern(e3d_filter, "*.e3d");
	
	e2d_filter=gtk_file_filter_new();
	gtk_file_filter_set_name(e2d_filter, "2D object");
	gtk_file_filter_add_pattern(e2d_filter, "*.2d0");
	
	map_filter=gtk_file_filter_new();
	gtk_file_filter_set_name(map_filter, "Map file");
	gtk_file_filter_add_pattern(map_filter, "*.elm");
	
	part_filter=gtk_file_filter_new();
	gtk_file_filter_set_name(part_filter, "Particle file");
	gtk_file_filter_add_pattern(part_filter, "*.part");
}

void show_open_window(char * name, char * folder, GtkFileFilter * filter)
{
	if(!gtk_open_win) {
		gtk_open_win=gtk_file_chooser_dialog_new(name, NULL, GTK_FILE_CHOOSER_ACTION_OPEN,
			GTK_STOCK_CANCEL, GTK_RESPONSE_CANCEL, //Cancel button
			GTK_STOCK_OPEN, GTK_RESPONSE_ACCEPT,//Open button
			NULL);
		gtk_file_chooser_add_filter(GTK_FILE_CHOOSER(gtk_open_win), e3d_filter);
		gtk_file_chooser_add_filter(GTK_FILE_CHOOSER(gtk_open_win), e2d_filter);
		gtk_file_chooser_add_filter(GTK_FILE_CHOOSER(gtk_open_win), map_filter);
		gtk_file_chooser_add_filter(GTK_FILE_CHOOSER(gtk_open_win), part_filter);
	} else {
		gtk_window_set_title(GTK_WINDOW(gtk_open_win), name);
	}
	
	gtk_file_chooser_set_filter(GTK_FILE_CHOOSER(gtk_open_win), filter);
	gtk_file_chooser_set_current_folder(GTK_FILE_CHOOSER(gtk_open_win), folder);
	
	if(gtk_dialog_run(GTK_DIALOG(gtk_open_win)) == GTK_RESPONSE_ACCEPT) {
		selected_file = gtk_file_chooser_get_filename(GTK_FILE_CHOOSER(gtk_open_win));
		filter=gtk_file_chooser_get_filter(GTK_FILE_CHOOSER(gtk_open_win));
		if(selected_file){
			//What should we do next...
			if((point)filter==(point)map_filter){
				strcpy(map_file_name, selected_file);
				open_map_file_continued();
			} else if((point)filter==(point)e3d_filter){
				open_3d_obj_continued();
			} else if((point)filter==(point)e2d_filter){
				open_2d_obj_continued();
			} else if((point)filter==(point)part_filter){
				strcpy(particle_file_name, selected_file);
				open_particles_obj_continued();
			}
			
			g_free(selected_file);
		}
	}
	
	gtk_widget_hide(gtk_open_win);
}

void show_save_window(char * name, char * folder, char * select, GtkFileFilter * filter)
{
	if(!gtk_save_win) {
		gtk_save_win=gtk_file_chooser_dialog_new(name, NULL, GTK_FILE_CHOOSER_ACTION_SAVE,
			GTK_STOCK_CANCEL, GTK_RESPONSE_CANCEL, //Cancel button
			GTK_STOCK_SAVE, GTK_RESPONSE_ACCEPT,//Open button
			NULL);
		/*gtk_file_chooser_add_filter(GTK_FILE_CHOOSER(gtk_open_win), map_filter);
		gtk_file_chooser_add_filter(GTK_FILE_CHOOSER(gtk_open_win), part_filter);*/
	} else {
		gtk_window_set_title(GTK_WINDOW(gtk_save_win), name);
	}
	
	gtk_file_chooser_set_filter(GTK_FILE_CHOOSER(gtk_save_win), filter);
	gtk_file_chooser_set_current_folder(GTK_FILE_CHOOSER(gtk_save_win), folder);
	if(select[0])gtk_file_chooser_set_filename(GTK_FILE_CHOOSER(gtk_save_win), select);
	else gtk_file_chooser_set_current_name(GTK_FILE_CHOOSER(gtk_save_win), "my_map.elm");

	if(gtk_dialog_run(GTK_DIALOG(gtk_save_win)) == GTK_RESPONSE_ACCEPT) {
		selected_file = gtk_file_chooser_get_filename(GTK_FILE_CHOOSER(gtk_save_win));
		filter=gtk_file_chooser_get_filter(GTK_FILE_CHOOSER(gtk_save_win));
		if(selected_file){
			//What should we do next...
			if((point)filter==(point)map_filter){
				strcpy(map_file_name, selected_file);
				save_map_file_continued();
			} else if((point)filter==(point)part_filter){
				strcpy(particle_file_name, selected_file);
				save_particle_def_file_continued();
			}

			gtk_file_chooser_unselect_filename(GTK_FILE_CHOOSER(gtk_save_win), selected_file);
			g_free(selected_file);
		}
	}

	gtk_widget_hide(gtk_save_win);
}

#else
/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "gui_callbacks.h"
#include "gui.h"
#include "gui_support.h"

GtkWidget*
create_fileselection (void)
{
  GtkWidget *fileselection;
  GtkWidget *ok_button1;
  GtkWidget *cancel_button1;

  fileselection = gtk_file_selection_new ("Select File");
  gtk_object_set_data (GTK_OBJECT (fileselection), "fileselection", fileselection);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection), 10);
  GTK_WINDOW (fileselection)->type = GTK_WINDOW_DIALOG;

  ok_button1 = GTK_FILE_SELECTION (fileselection)->ok_button;
  gtk_object_set_data (GTK_OBJECT (fileselection), "ok_button1", ok_button1);
  gtk_widget_show (ok_button1);
  GTK_WIDGET_SET_FLAGS (ok_button1, GTK_CAN_DEFAULT);

  cancel_button1 = GTK_FILE_SELECTION (fileselection)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (fileselection), "cancel_button1", cancel_button1);
  gtk_widget_show (cancel_button1);
  GTK_WIDGET_SET_FLAGS (cancel_button1, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (ok_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_button1_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cancel_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_button1_clicked),
                      NULL);

  gtk_file_selection_hide_fileop_buttons( GTK_FILE_SELECTION (fileselection));

  return fileselection;
}
#endif
