/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#define OPEN_3D_OBJ 1
#define OPEN_2D_OBJ 2
#define OPEN_MAP    3
#define SAVE_MAP    4
#define OPEN_PARTICLES_OBJ 5
#define SAVE_PARTICLE_DEF 6
#define OPEN_EYE_CANDY_OBJ 7

extern char* selected_file;

#ifdef GTK2
extern char map_file_name[256];
extern char particle_file_name[256];
extern char map_folder[256];
extern char obj_2d_folder[256];
extern char obj_3d_folder[256];
extern char particles_folder[256];

extern GtkFileFilter * e3d_filter;
extern GtkFileFilter * e2d_filter;
extern GtkFileFilter * map_filter;
extern GtkFileFilter * part_filter;

void init_filters();
void show_open_window(char * name, char * folder, GtkFileFilter * filter);
void show_save_window(char * name, char * folder, char * select, GtkFileFilter *filter);
void show_eye_candy_window();
#else
extern int continue_with;
extern GtkWidget* file_selector;
extern GtkWidget* effect_selector;
extern GtkWidget* create_fileselection (void);
#endif
