.TH EL.LINUX.BIN 6 "Dec 2020" "1.9.5" "Eternal Lands Client"

.SH NAME
el.linux.bin - Client for Eternal Lands, a free MMORPG

.SH SYNOPSIS
.B el.linux.bin
[
.I <tdb other options> <config name>
]

.SH DESCRIPTION
Eternal Lands is a free MMORPG (massively multi-player online role playing 
game).


.SH Web Resources

.TP
.I The main website for the game
http://www.eternal-lands.com/

.TP
.I Game Forums
http://www.eternal-lands.com/forum/

.TP
.I Client Source Code
https://github.com/raduprv/Eternal-Lands

.TP
.I Ubuntu & debian packages
https://twinmoons.org.uk/el_linux_packages.html

.SH COPYRIGHT
Copyright (C) 2003-2020, Radu Privantu and Maura Privantu.
