.TH EL.X86.LINUX.BIN 6 "Feb 2012" "el.x86.linux.bin.1.9.3" "Eternal Lands Client"

.SH NAME
el.x86.linux.bin - Client for the Eternal Lands, a free MMORPG

.SH SYNOPSIS
.B el.x86.linux.bin
[
.I <config name> <tdb other options>
]

.SH DESCRIPTION
Eternal Lands is a free MMORPG (massively multi-player online role playing 
game).


.SH Web Resources

.TP
.I The main website for the game
http://www.eternal-lands.com/

.TP
.I Game Forums
http://www.eternal-lands.com/forum/

.TP
.I Client Source Code
https://github.com/raduprv/Eternal-Lands

.TP
.I Ubuntu & debian packages
https://help.ubuntu.com/community/EternalLands

.TP

.SH COPYRIGHT
Copyright (C) 2003-2012, Radu Privantu and Maura Privantu.
