.TH ETERNALLANDS 6 "April 2010" "eternallands-0.0.2" "Eternal Lands Wrapper Script"

.SH NAME
eternallands - Wrapper script for the Eternal Lands MMORPG client

.SH SYNOPSIS
.B eternallands
[
.I <pass through options>
]

.SH DESCRIPTION
Eternal Lands is a FREE MMORPG (massively multi-player online role playing 
game). This script provides a wrapper for the client.  It checks that the users
~/.elc/ directory exists and that the files ~/.elc/server.lst and
~/.elc/main/el.ini exist.  If these files do not exist then they will be copied
from the version shipped with the eternallands-data package.  The data_dir entry
for all ~/.elc/*/el.ini files is tested.  If any do not refer to the installed
eternallands-data package, the user is offered the option to fix the path.  The 
Eternal Lands client is then run, passed any command line options specified for
this script.  Finally, if the client exits with an error status, a window is 
opened to inform the user, offering advice on resolving the problem and showing
a copy of the ~/.elc/error_log.txt file.  All user interaction is done using 
the zenity program.

.SH FILES
.I ~/.elc/showconfigsel
.RS
If exists and contains the word no, use of the configuration selection window
is disabled.
.RE
.I ~/.elc/no.el.ini.check
.RS
If exists, disable the check for correct data_dir paths in el.ini files.
.RE
.I ~/.elc/el_client
.RS
If exists, the file should contain the full path to an alternative client
executable.
.RE

.SH COPYRIGHT
This program (script), and only this script from the eternallands
package is released as Public Domain software.  You are free to use
it as you wish.  There is NO  warranty; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.

.SH AUTHOR
Paul Broadhead (a.k.a. bluap) pjbroad@twinmoons.org.uk
