#!/usr/bin/env bash
#
# Wrapper script for Eternal Lands client.
# - Copies required files to ~/.elc if not already there
# - Checks all ~/.elc/ tree el.ini files have correct and optionall fixes them
# - optionally displays a server/configuration selection GUI
#
# Author Paul Broadhead pjbroad@twinmoons.clara.co.uk
#
# This program (script), and only this script from the eternallands
# package is released as Public Domain software.  You are free to use
# it as you wish.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#

# get users choice from the $serverfile
getconfig()
{
	grep -v ^# $serverfile | sort | tr -d '\015' | \
	while read name dir server port description
	do
		echo $name
		echo $description
		echo $server
		echo $port
		echo $dir
	done | \
	zenity --title="Eternal Lands Launcher" --width=450 --height=280 \
		--list \
		--column "Name" \
		--column "Description" \
		--column "Server" \
		--column "Port" \
		--column "Directory" \
		--text "Select Server/Configuration"
}

# make sure the user config tree exists
mkdir -p ~/.elc/main

# copy a servers.lst file as we don't have one
serverfile=~/.elc/servers.lst
if [ ! -r $serverfile -o ! -s $serverfile ]
then
	cp -p /usr/share/games/EternalLands/servers.lst $serverfile
fi

# copy an el.ini file as we don't have one
if [ ! -r ~/.elc/main/el.ini -o ! -s $serverfile ]
then
	cp -p /usr/share/games/EternalLands/el.ini ~/.elc/main/el.ini
fi

# make sure we have permissions on config files
[ ! -r $serverfile -o ! -w $serverfile ] && chmod +wr $serverfile
for i in $(find ~/.elc/ -name el.ini)
do
	[ ! -r $i -o ! -w $i ] && chmod +wr $i
done

# check el.ini files point to installed data
if [ ! -r ~/.elc/no.el.ini.check ]
then
	show_suppression=false
	for i in $(find ~/.elc/ -name el.ini)
	do
		if [ "$(grep ^#data_dir $i | tail -1 | grep '^#data_dir = /usr/share/games/EternalLands$')" = "" ]
		then
			if zenity --question --text="Warning: $i does not use installed game data, shall I fix this problem?"
			then
				sed -i 's/^#data_dir.*$/#data_dir = \/usr\/share\/games\/EternalLands/g' $i
			else
				show_suppression=true
			fi
		fi
	done
	if $show_suppression
	then
		zenity --info --text="To surpress these warnings, create the empty file ~/.elc/no.el.ini.check"
	fi
fi

config=""

# if no command line options specified, see if we want to use the config selection window
if [ "$*" = "" ]
then
	showsel=~/.elc/showconfigsel

	# optionally get the server/config option
	[ ! -r $showsel ] && touch $showsel
	if [ "$(grep no $showsel)" = "" ]
	then
		[ ! -s $showsel ] && rm -f $showsel
		config="$(getconfig)"
		[ $? -ne 0 ] && exit
	fi

	# if not already configured, choose if to use the server/configuration selection window
	if [ ! -r $showsel ]
	then
		if zenity --question --text="Always use the server/configuration selection window?"
		then
			echo "yes" > $showsel
		else
			echo "no" > $showsel
		fi
		zenity --info --text="To change this option, edit or remove the file ~/.elc/showconfigsel"
	fi
fi

# run the client, display error log if it crashes
if ! /usr/games/el.x86.linux.bin $config $*
then
	cat | zenity --text-info --width=500 --height=300 --title "Eternal Lands Crashed, this is the Error log." << EOT
Oh my, Eternal Lands Crashed - Don't Panic!

A couple of things you can try:
1) Make sure your system is up to date, especially your video drivers.
2) If you crash repeatedly during the login process, try setting the "poor man" option from the settings window: At the login screen, click "Settings" select the "Details" tab and set the "Poor Man" option.

If you continue to have problems check the Eternal Lands forums, especially the "Help Me" and "Bug Report" sections.  If you post a message make sure you include information about your system; i.e video driver and version, operating system and version.  Make sure you check your error log for clues too and include the contents in any forum report.

The following is your error log contents.  Note it is overwritten each time you run the game.

$(cat ~/.elc/error_log.txt)
EOT
fi

