native set_object_rotation (id, Float: rot_x, Float: rot_y, Float: rot_z);
native rotate_object (id, Float: rot_x, Float: rot_y, Float: rot_z);
native rotate_object_add (id, Float: rot_x, Float: rot_y, Float: rot_z);

native set_object_position (id, Float: rot_x, Float: rot_y, Float: rot_z);
native translate_object (id, Float: rot_x, Float: rot_y, Float: rot_z);

native log_to_console (const format[], {Float,Fixed,_}:...);
