#if defined _features_included
\t#endinput
#endif
#define _features_included
#define CLUSTER_INSIDES
#define CUSTOM_LOOK
#define CUSTOM_UPDATE
#define FUZZY_PATHS
#define NEW_SOUND
#define PNG_SCREENSHOT
#define USE_INLINE
#define BANDWIDTH_SAVINGS
#define ANIMATION_SCALING
#define FSAA
#define FASTER_MAP_LOAD
#define FASTER_STARTUP
#define MIDDLE_MOUSE_PASTE
#define NEW_EYES
#define NEW_CURSOR
#define JSON_FILES
#define TTF
#define ECDEBUGWIN
#define OPENGL_TRACE
#define PAWN
